In [1]:
from scipy.spatial import cKDTree
import numpy as np
import pandas as pd

In [4]:
y = np.arange(0, 100000).reshape(-1, 2)

In [7]:
x = np.arange(0, 100000).reshape(-1, 2)

In [8]:
combined_x_y_arrays = np.dstack([y.ravel(), x.ravel()])[0]

In [9]:
combined_x_y_arrays

array([[    0,     0],
       [    1,     1],
       [    2,     2],
       ...,
       [99997, 99997],
       [99998, 99998],
       [99999, 99999]])

In [10]:
points = np.arange(0, 10).reshape(-1, 2)

In [11]:
points

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [2]:
from datetime import datetime
for n in [10, 100, 1000, 10000, 100000, 1000000]:
    x = np.arange(0, n).reshape(-1, 2)
    y = np.arange(0, n).reshape(-1, 2)
    combined_x_y_arrays = np.dstack([x.ravel(), y.ravel()])[0]
    time_tmp = datetime.now()
    kdtree = cKDTree(combined_x_y_arrays)
    print(datetime.now() - time_tmp)

0:00:00.000129
0:00:00.000193
0:00:00.002457
0:00:00.190637
0:00:18.916771
0:31:31.251516


In [18]:
kdtree.query(points)

(array([9.        , 7.28010989, 6.40312424, 6.40312424, 6.40312424]),
 array([0, 0, 0, 1, 3]))

In [1]:
import h5py

In [2]:
file_name = '/home/cali/src/gap_filling/Data/650.0_1095.0_1210.0_1750.0_2155.0_2550.0_2550.625_2755.0.hdf'

In [3]:
hdf5 = h5py.File(file_name, 'r')

In [4]:
hdf5.keys()

<KeysViewHDF5 ['index_X', 'index_Y', 'test_X', 'test_Y', 'train_X', 'train_Y', 'wavenumber_X', 'wavenumber_Y']>

In [5]:
hdf5.close()